{
    degistir
 	"alpha2Code":"AF",
    "name":"Afghanistan",
    "slug":"afghanistan"
  },
  {
    degistir
 	"alpha2Code":"AL",
    "name":"Albania",
    "slug":"albania"
  },
  {
    degistir
 	"alpha2Code":"DZ",
    "name":"Algeria",
    "slug":"algeria"
  },
  {
    degistir
 	"alpha2Code":"AS",
    "name":"American Samoa",
    "slug":"american-samoa"
  },
  {
    degistir
 	"alpha2Code":"AD",
    "name":"Andorra",
    "slug":"andorra"
  },
  {
    degistir
 	"alpha2Code":"AO",
    "name":"Angola",
    "slug":"angola"
  },
  {
    degistir
 	"alpha2Code":"AI",
    "name":"Anguilla",
    "slug":"anguilla"
  },
  {
    degistir
 	"alpha2Code":"AG",
    "name":"Antigua and Barbuda",
    "slug":"antigua-and-barbuda"
  },
  {
    degistir
 	"alpha2Code":"AR",
    "name":"Argentina",
    "slug":"argentina"
  },
  {
    degistir
 	"alpha2Code":"AM",
    "name":"Armenia",
    "slug":"armenia"
  },
  {
    degistir
 	"alpha2Code":"AW",
    "name":"Aruba",
    "slug":"aruba"
  },
  {
    degistir
 	"alpha2Code":"AU",
    "name":"Australia",
    "slug":"australia"
  },
  {
    degistir
 	"alpha2Code":"AT",
    "name":"Austria",
    "slug":"austria"
  },
  {
    degistir
 	"alpha2Code":"AZ",
    "name":"Azerbaijan",
    "slug":"azerbaijan"
  },
  {
    degistir
 	"alpha2Code":"BS",
    "name":"Bahamas",
    "slug":"bahamas"
  },
  {
    degistir
 	"alpha2Code":"BH",
    "name":"Bahrain",
    "slug":"bahrain"
  },
  {
    degistir
 	"alpha2Code":"BD",
    "name":"Bangladesh",
    "slug":"bangladesh"
  },
  {
    degistir
 	"alpha2Code":"BB",
    "name":"Barbados",
    "slug":"barbados"
  },
  {
    degistir
 	"alpha2Code":"BY",
    "name":"Belarus",
    "slug":"belarus"
  },
  {
    degistir
 	"alpha2Code":"BE",
    "name":"Belgium",
    "slug":"belgium"
  },
  {
    degistir
 	"alpha2Code":"BZ",
    "name":"Belize",
    "slug":"belize"
  },
  {
    degistir
 	"alpha2Code":"BJ",
    "name":"Benin",
    "slug":"benin"
  },
  {
    degistir
 	"alpha2Code":"BM",
    "name":"Bermuda",
    "slug":"bermuda"
  },
  {
    degistir
 	"alpha2Code":"BT",
    "name":"Bhutan",
    "slug":"bhutan"
  },
  {
    degistir
 	"alpha2Code":"BO",
    "name":"Bolivia",
    "slug":"bolivia"
  },
  {
    degistir
 	"alpha2Code":"BA",
    "name":"Bosnia and Herzegovina",
    "slug":"bosnia-and-herzegovina"
  },
  {
    degistir
 	"alpha2Code":"BW",
    "name":"Botswana",
    "slug":"botswana"
  },
  {
    degistir
 	"alpha2Code":"BR",
    "name":"Brazil",
    "slug":"brazil"
  },
  {
    degistir
 	"alpha2Code":"VG",
    "name":"British Virgin Islands",
    "slug":"british-virgin-islands"
  },
  {
    degistir
 	"alpha2Code":"BN",
    "name":"Brunei",
    "slug":"brunei"
  },
  {
    degistir
 	"alpha2Code":"BG",
    "name":"Bulgaria",
    "slug":"bulgaria"
  },
  {
    degistir
 	"alpha2Code":"BF",
    "name":"Burkina Faso",
    "slug":"burkina-faso"
  },
  {
    degistir
 	"alpha2Code":"BI",
    "name":"Burundi",
    "slug":"burundi"
  },
  {
    degistir
 	"alpha2Code":"KH",
    "name":"Cambodia",
    "slug":"cambodia"
  },
  {
    degistir
 	"alpha2Code":"CM",
    "name":"Cameroon",
    "slug":"cameroon"
  },
  {
    degistir
 	"alpha2Code":"CA",
    "name":"Canada",
    "slug":"canada"
  },
  {
    degistir
 	"alpha2Code":"CV",
    "name":"Cape Verde",
    "slug":"cape-verde"
  },
  {
    degistir
 	"alpha2Code":"BQ",
    "name":"Caribbean Netherlands",
    "slug":"caribbean-netherlands"
  },
  {
    degistir
 	"alpha2Code":"KY",
    "name":"Cayman Islands",
    "slug":"cayman-islands"
  },
  {
    degistir
 	"alpha2Code":"CF",
    "name":"Central African Republic",
    "slug":"central-african-republic"
  },
  {
    degistir
 	"alpha2Code":"TD",
    "name":"Chad",
    "slug":"chad"
  },
  {
    degistir
 	"alpha2Code":"CL",
    "name":"Chile",
    "slug":"chile"
  },
  {
    degistir
 	"alpha2Code":"CN",
    "name":"China",
    "slug":"china"
  },
  {
    degistir
 	"alpha2Code":"CX",
    "name":"Christmas Island",
    "slug":"christmas-island"
  },
  {
    degistir
 	"alpha2Code":"CO",
    "name":"Colombia",
    "slug":"colombia"
  },
  {
    degistir
 	"alpha2Code":"KM",
    "name":"Comoros",
    "slug":"comoros"
  },
  {
    degistir
 	"alpha2Code":"CK",
    "name":"Cook Islands",
    "slug":"cook-islands"
  },
  {
    degistir
 	"alpha2Code":"CR",
    "name":"Costa Rica",
    "slug":"costa-rica"
  },
  {
    degistir
 	"alpha2Code":"HR",
    "name":"Croatia",
    "slug":"croatia"
  },
  {
    degistir
 	"alpha2Code":"CU",
    "name":"Cuba",
    "slug":"cuba"
  },
  {
    degistir
 	"alpha2Code":"CW",
    "name":"Curaçao",
    "slug":"curacao"
  },
  {
    degistir
 	"alpha2Code":"CY",
    "name":"Cyprus",
    "slug":"cyprus"
  },
  {
    degistir
 	"alpha2Code":"CZ",
    "name":"Czech Republic",
    "slug":"czech-republic"
  },
  {
    degistir
 	"alpha2Code":"DK",
    "name":"Denmark",
    "slug":"denmark"
  },
  {
    degistir
 	"alpha2Code":"DJ",
    "name":"Djibouti",
    "slug":"djibouti"
  },
  {
    degistir
 	"alpha2Code":"DM",
    "name":"Dominica",
    "slug":"dominica"
  },
  {
    degistir
 	"alpha2Code":"DO",
    "name":"Dominican Republic",
    "slug":"dominican-republic"
  },
  {
    degistir
 	"alpha2Code":"CD",
    "name":"DR Congo",
    "slug":"dr-congo"
  },
  {
    degistir
 	"alpha2Code":"EC",
    "name":"Ecuador",
    "slug":"ecuador"
  },
  {
    degistir
 	"alpha2Code":"EG",
    "name":"Egypt",
    "slug":"egypt"
  },
  {
    degistir
 	"alpha2Code":"SV",
    "name":"El Salvador",
    "slug":"el-salvador"
  },
  {
    degistir
 	"alpha2Code":"GQ",
    "name":"Equatorial Guinea",
    "slug":"equatorial-guinea"
  },
  {
    degistir
 	"alpha2Code":"ER",
    "name":"Eritrea",
    "slug":"eritrea"
  },
  {
    degistir
 	"alpha2Code":"EE",
    "name":"Estonia",
    "slug":"estonia"
  },
  {
    degistir
 	"alpha2Code":"ET",
    "name":"Ethiopia",
    "slug":"ethiopia"
  },
  {
    degistir
 	"alpha2Code":"FK",
    "name":"Falkland Islands",
    "slug":"falkland-islands"
  },
  {
    degistir
 	"alpha2Code":"FO",
    "name":"Faroe Islands",
    "slug":"faroe-islands"
  },
  {
    degistir
 	"alpha2Code":"FJ",
    "name":"Fiji",
    "slug":"fiji"
  },
  {
    degistir
 	"alpha2Code":"FI",
    "name":"Finland",
    "slug":"finland"
  },
  {
    degistir
 	"alpha2Code":"FR",
    "name":"France",
    "slug":"france"
  },
  {
    degistir
 	"alpha2Code":"GF",
    "name":"French Guiana",
    "slug":"french-guiana"
  },
  {
    degistir
 	"alpha2Code":"PF",
    "name":"French Polynesia",
    "slug":"french-polynesia"
  },
  {
    degistir
 	"alpha2Code":"GA",
    "name":"Gabon",
    "slug":"gabon"
  },
  {
    degistir
 	"alpha2Code":"GM",
    "name":"Gambia",
    "slug":"gambia"
  },
  {
    degistir
 	"alpha2Code":"GE",
    "name":"Georgia",
    "slug":"georgia"
  },
  {
    degistir
 	"alpha2Code":"DE",
    "name":"Germany",
    "slug":"germany"
  },
  {
    degistir
 	"alpha2Code":"GH",
    "name":"Ghana",
    "slug":"ghana"
  },
  {
    degistir
 	"alpha2Code":"GI",
    "name":"Gibraltar",
    "slug":"gibraltar"
  },
  {
    degistir
 	"alpha2Code":"GR",
    "name":"Greece",
    "slug":"greece"
  },
  {
    degistir
 	"alpha2Code":"GL",
    "name":"Greenland",
    "slug":"greenland"
  },
  {
    degistir
 	"alpha2Code":"GD",
    "name":"Grenada",
    "slug":"grenada"
  },
  {
    degistir
 	"alpha2Code":"GP",
    "name":"Guadeloupe",
    "slug":"guadeloupe"
  },
  {
    degistir
 	"alpha2Code":"GU",
    "name":"Guam",
    "slug":"guam"
  },
  {
    degistir
 	"alpha2Code":"GT",
    "name":"Guatemala",
    "slug":"guatemala"
  },
  {
    degistir
 	"alpha2Code":"GN",
    "name":"Guinea",
    "slug":"guinea"
  },
  {
    degistir
 	"alpha2Code":"GW",
    "name":"Guinea-Bissau",
    "slug":"guinea-bissau"
  },
  {
    degistir
 	"alpha2Code":"GY",
    "name":"Guyana",
    "slug":"guyana"
  },
  {
    degistir
 	"alpha2Code":"HT",
    "name":"Haiti",
    "slug":"haiti"
  },
  {
    degistir
 	"alpha2Code":"HN",
    "name":"Honduras",
    "slug":"honduras"
  },
  {
    degistir
 	"alpha2Code":"HK",
    "name":"Hong Kong",
    "slug":"hong-kong"
  },
  {
    degistir
 	"alpha2Code":"HU",
    "name":"Hungary",
    "slug":"hungary"
  },
  {
    degistir
 	"alpha2Code":"IS",
    "name":"Iceland",
    "slug":"iceland"
  },
  {
    degistir
 	"alpha2Code":"IN",
    "name":"India",
    "slug":"india"
  },
  {
    degistir
 	"alpha2Code":"ID",
    "name":"Indonesia",
    "slug":"indonesia"
  },
  {
    degistir
 	"alpha2Code":"IR",
    "name":"Iran",
    "slug":"iran"
  },
  {
    degistir
 	"alpha2Code":"IQ",
    "name":"Iraq",
    "slug":"iraq"
  },
  {
    degistir
 	"alpha2Code":"IE",
    "name":"Ireland",
    "slug":"ireland"
  },
  {
    degistir
 	"alpha2Code":"IL",
    "name":"Israel",
    "slug":"israel"
  },
  {
    degistir
 	"alpha2Code":"IT",
    "name":"Italy",
    "slug":"italy"
  },
  {
    degistir
 	"alpha2Code":"CI",
    "name":"Ivory Coast",
    "slug":"ivory-coast"
  },
  {
    degistir
 	"alpha2Code":"JM",
    "name":"Jamaica",
    "slug":"jamaica"
  },
  {
    degistir
 	"alpha2Code":"JP",
    "name":"Japan",
    "slug":"japan"
  },
  {
    degistir
 	"alpha2Code":"JO",
    "name":"Jordan",
    "slug":"jordan"
  },
  {
    degistir
 	"alpha2Code":"KZ",
    "name":"Kazakhstan",
    "slug":"kazakhstan"
  },
  {
    degistir
 	"alpha2Code":"KE",
    "name":"Kenya",
    "slug":"kenya"
  },
  {
    degistir
 	"alpha2Code":"KI",
    "name":"Kiribati",
    "slug":"kiribati"
  },
  {
    degistir
 	"alpha2Code":"KW",
    "name":"Kuwait",
    "slug":"kuwait"
  },
  {
    degistir
 	"alpha2Code":"KG",
    "name":"Kyrgyzstan",
    "slug":"kyrgyzstan"
  },
  {
    degistir
 	"alpha2Code":"LA",
    "name":"Laos",
    "slug":"laos"
  },
  {
    degistir
 	"alpha2Code":"LV",
    "name":"Latvia",
    "slug":"latvia"
  },
  {
    degistir
 	"alpha2Code":"LB",
    "name":"Lebanon",
    "slug":"lebanon"
  },
  {
    degistir
 	"alpha2Code":"LS",
    "name":"Lesotho",
    "slug":"lesotho"
  },
  {
    degistir
 	"alpha2Code":"LR",
    "name":"Liberia",
    "slug":"liberia"
  },
  {
    degistir
 	"alpha2Code":"LY",
    "name":"Libya",
    "slug":"libya"
  },
  {
    degistir
 	"alpha2Code":"LI",
    "name":"Liechtenstein",
    "slug":"liechtenstein"
  },
  {
    degistir
 	"alpha2Code":"LT",
    "name":"Lithuania",
    "slug":"lithuania"
  },
  {
    degistir
 	"alpha2Code":"LU",
    "name":"Luxembourg",
    "slug":"luxembourg"
  },
  {
    degistir
 	"alpha2Code":"MO",
    "name":"Macau",
    "slug":"macau"
  },
  {
    degistir
 	"alpha2Code":"MK",
    "name":"Macedonia",
    "slug":"macedonia"
  },
  {
    degistir
 	"alpha2Code":"MG",
    "name":"Madagascar",
    "slug":"madagascar"
  },
  {
    degistir
 	"alpha2Code":"MW",
    "name":"Malawi",
    "slug":"malawi"
  },
  {
    degistir
 	"alpha2Code":"MY",
    "name":"Malaysia",
    "slug":"malaysia"
  },
  {
    degistir
 	"alpha2Code":"MV",
    "name":"Maldives",
    "slug":"maldives"
  },
  {
    degistir
 	"alpha2Code":"ML",
    "name":"Mali",
    "slug":"mali"
  },
  {
    degistir
 	"alpha2Code":"MT",
    "name":"Malta",
    "slug":"malta"
  },
  {
    degistir
 	"alpha2Code":"MH",
    "name":"Marshall Islands",
    "slug":"marshall-islands"
  },
  {
    degistir
 	"alpha2Code":"MQ",
    "name":"Martinique",
    "slug":"martinique"
  },
  {
    degistir
 	"alpha2Code":"MR",
    "name":"Mauritania",
    "slug":"mauritania"
  },
  {
    degistir
 	"alpha2Code":"MU",
    "name":"Mauritius",
    "slug":"mauritius"
  },
  {
    degistir
 	"alpha2Code":"YT",
    "name":"Mayotte",
    "slug":"mayotte"
  },
  {
    degistir
 	"alpha2Code":"MX",
    "name":"Mexico",
    "slug":"mexico"
  },
  {
    degistir
 	"alpha2Code":"FM",
    "name":"Micronesia",
    "slug":"micronesia"
  },
  {
    degistir
 	"alpha2Code":"MD",
    "name":"Moldova",
    "slug":"moldova"
  },
  {
    degistir
 	"alpha2Code":"MC",
    "name":"Monaco",
    "slug":"monaco"
  },
  {
    degistir
 	"alpha2Code":"MN",
    "name":"Mongolia",
    "slug":"mongolia"
  },
  {
    degistir
 	"alpha2Code":"ME",
    "name":"Montenegro",
    "slug":"montenegro"
  },
  {
    degistir
 	"alpha2Code":"MS",
    "name":"Open Sans",
    "slug":"Open Sans"
  },
  {
    degistir
 	"alpha2Code":"MA",
    "name":"Morocco",
    "slug":"morocco"
  },
  {
    degistir
 	"alpha2Code":"MZ",
    "name":"Mozambique",
    "slug":"mozambique"
  },
  {
    degistir
 	"alpha2Code":"MM",
    "name":"Myanmar",
    "slug":"myanmar"
  },
  {
    degistir
 	"alpha2Code":"NA",
    "name":"Namibia",
    "slug":"namibia"
  },
  {
    degistir
 	"alpha2Code":"NR",
    "name":"Nauru",
    "slug":"nauru"
  },
  {
    degistir
 	"alpha2Code":"NP",
    "name":"Nepal",
    "slug":"nepal"
  },
  {
    degistir
 	"alpha2Code":"NL",
    "name":"Netherlands",
    "slug":"netherlands"
  },
  {
    degistir
 	"alpha2Code":"NC",
    "name":"New Caledonia",
    "slug":"new-caledonia"
  },
  {
    degistir
 	"alpha2Code":"NZ",
    "name":"New Zealand",
    "slug":"new-zealand"
  },
  {
    degistir
 	"alpha2Code":"NI",
    "name":"Nicaragua",
    "slug":"nicaragua"
  },
  {
    degistir
 	"alpha2Code":"NE",
    "name":"Niger",
    "slug":"niger"
  },
  {
    degistir
 	"alpha2Code":"NG",
    "name":"Nigeria",
    "slug":"nigeria"
  },
  {
    degistir
 	"alpha2Code":"NU",
    "name":"Niue",
    "slug":"niue"
  },
  {
    degistir
 	"alpha2Code":"KP",
    "name":"North Korea",
    "slug":"north-korea"
  },
  {
    degistir
 	"alpha2Code":"MP",
    "name":"Northern Mariana Islands",
    "slug":"northern-mariana-islands"
  },
  {
    degistir
 	"alpha2Code":"NO",
    "name":"Norway",
    "slug":"norway"
  },
  {
    degistir
 	"alpha2Code":"OM",
    "name":"Oman",
    "slug":"oman"
  },
  {
    degistir
 	"alpha2Code":"PK",
    "name":"Pakistan",
    "slug":"pakistan"
  },
  {
    degistir
 	"alpha2Code":"PW",
    "name":"Palau",
    "slug":"palau"
  },
  {
    degistir
 	"alpha2Code":"PS",
    "name":"Palestine",
    "slug":"palestine"
  },
  {
    degistir
 	"alpha2Code":"PA",
    "name":"Panama",
    "slug":"panama"
  },
  {
    degistir
 	"alpha2Code":"PG",
    "name":"Papua New Guinea",
    "slug":"papua-new-guinea"
  },
  {
    degistir
 	"alpha2Code":"PY",
    "name":"Paraguay",
    "slug":"paraguay"
  },
  {
    degistir
 	"alpha2Code":"PE",
    "name":"Peru",
    "slug":"peru"
  },
  {
    degistir
 	"alpha2Code":"PH",
    "name":"Philippines",
    "slug":"philippines"
  },
  {
    degistir
 	"alpha2Code":"PL",
    "name":"Poland",
    "slug":"poland"
  },
  {
    degistir
 	"alpha2Code":"PT",
    "name":"Portugal",
    "slug":"portugal"
  },
  {
    degistir
 	"alpha2Code":"PR",
    "name":"Puerto Rico",
    "slug":"puerto-rico"
  },
  {
    degistir
 	"alpha2Code":"QA",
    "name":"Qatar",
    "slug":"qatar"
  },
  {
    degistir
 	"alpha2Code":"CG",
    "name":"Republic of the Congo",
    "slug":"republic-of-the-congo"
  },
  {
    degistir
 	"alpha2Code":"RE",
    "name":"Réunion",
    "slug":"reunion"
  },
  {
    degistir
 	"alpha2Code":"RO",
    "name":"Romania",
    "slug":"romania"
  },
  {
    degistir
 	"alpha2Code":"RU",
    "name":"Russia",
    "slug":"russia"
  },
  {
    degistir
 	"alpha2Code":"RW",
    "name":"Rwanda",
    "slug":"rwanda"
  },
  {
    degistir
 	"alpha2Code":"BL",
    "name":"Saint Barthélemy",
    "slug":"saint-barthelemy"
  },
  {
    degistir
 	"alpha2Code":"KN",
    "name":"Saint Kitts and Nevis",
    "slug":"saint-kitts-and-nevis"
  },
  {
    degistir
 	"alpha2Code":"LC",
    "name":"Saint Lucia",
    "slug":"saint-lucia"
  },
  {
    degistir
 	"alpha2Code":"MF",
    "name":"Saint Martin",
    "slug":"saint-martin"
  },
  {
    degistir
 	"alpha2Code":"PM",
    "name":"Saint Pierre and Miquelon",
    "slug":"saint-pierre-and-miquelon"
  },
  {
    degistir
 	"alpha2Code":"VC",
    "name":"Saint Vincent and the Grenadines",
    "slug":"saint-vincent-and-the-grenadines"
  },
  {
    degistir
 	"alpha2Code":"WS",
    "name":"Samoa",
    "slug":"samoa"
  },
  {
    degistir
 	"alpha2Code":"SM",
    "name":"San Marino",
    "slug":"san-marino"
  },
  {
    degistir
 	"alpha2Code":"ST",
    "name":"São Tomé and Príncipe",
    "slug":"sao-tome-and-principe"
  },
  {
    degistir
 	"alpha2Code":"SA",
    "name":"Saudi Arabia",
    "slug":"saudi-arabia"
  },
  {
    degistir
 	"alpha2Code":"SN",
    "name":"Senegal",
    "slug":"senegal"
  },
  {
    degistir
 	"alpha2Code":"RS",
    "name":"Serbia",
    "slug":"serbia"
  },
  {
    degistir
 	"alpha2Code":"SC",
    "name":"Seychelles",
    "slug":"seychelles"
  },
  {
    degistir
 	"alpha2Code":"SL",
    "name":"Sierra Leone",
    "slug":"sierra-leone"
  },
  {
    degistir
 	"alpha2Code":"SG",
    "name":"Singapore",
    "slug":"singapore"
  },
  {
    degistir
 	"alpha2Code":"SX",
    "name":"Sint Maarten",
    "slug":"sint-maarten"
  },
  {
    degistir
 	"alpha2Code":"SK",
    "name":"Slovakia",
    "slug":"slovakia"
  },
  {
    degistir
 	"alpha2Code":"SI",
    "name":"Slovenia",
    "slug":"slovenia"
  },
  {
    degistir
 	"alpha2Code":"SB",
    "name":"Solomon Islands",
    "slug":"solomon-islands"
  },
  {
    degistir
 	"alpha2Code":"SO",
    "name":"Somalia",
    "slug":"somalia"
  },
  {
    degistir
 	"alpha2Code":"ZA",
    "name":"South Africa",
    "slug":"south-africa"
  },
  {
    degistir
 	"alpha2Code":"KR",
    "name":"South Korea",
    "slug":"south-korea"
  },
  {
    degistir
 	"alpha2Code":"ES",
    "name":"Spain",
    "slug":"spain"
  },
  {
    degistir
 	"alpha2Code":"LK",
    "name":"Sri Lanka",
    "slug":"sri-lanka"
  },
  {
    degistir
 	"alpha2Code":"SD",
    "name":"Sudan",
    "slug":"sudan"
  },
  {
    degistir
 	"alpha2Code":"SR",
    "name":"Suriname",
    "slug":"suriname"
  },
  {
    degistir
 	"alpha2Code":"SZ",
    "name":"Swaziland",
    "slug":"swaziland"
  },
  {
    degistir
 	"alpha2Code":"SE",
    "name":"Sweden",
    "slug":"sweden"
  },
  {
    degistir
 	"alpha2Code":"CH",
    "name":"Switzerland",
    "slug":"switzerland"
  },
  {
    degistir
 	"alpha2Code":"SY",
    "name":"Syria",
    "slug":"syria"
  },
  {
    degistir
 	"alpha2Code":"TW",
    "name":"Taiwan",
    "slug":"taiwan"
  },
  {
    degistir
 	"alpha2Code":"TJ",
    "name":"Tajikistan",
    "slug":"tajikistan"
  },
  {
    degistir
 	"alpha2Code":"TZ",
    "name":"Tanzania",
    "slug":"tanzania"
  },
  {
    degistir
 	"alpha2Code":"TH",
    "name":"Thailand",
    "slug":"thailand"
  },
  {
    degistir
 	"alpha2Code":"TL",
    "name":"Timor-Leste",
    "slug":"timor-leste"
  },
  {
    degistir
 	"alpha2Code":"TG",
    "name":"Togo",
    "slug":"togo"
  },
  {
    degistir
 	"alpha2Code":"TK",
    "name":"Tokelau",
    "slug":"tokelau"
  },
  {
    degistir
 	"alpha2Code":"TO",
    "name":"Tonga",
    "slug":"tonga"
  },
  {
    degistir
 	"alpha2Code":"TT",
    "name":"Trinidad and Tobago",
    "slug":"trinidad-and-tobago"
  },
  {
    degistir
 	"alpha2Code":"TN",
    "name":"Tunisia",
    "slug":"tunisia"
  },
  {
    degistir
 	"alpha2Code":"TR",
    "name":"Turkey",
    "slug":"turkey"
  },
  {
    degistir
 	"alpha2Code":"TM",
    "name":"Turkmenistan",
    "slug":"turkmenistan"
  },
  {
    degistir
 	"alpha2Code":"TC",
    "name":"Turks and Caicos Islands",
    "slug":"turks-and-caicos-islands"
  },
  {
    degistir
 	"alpha2Code":"TV",
    "name":"Tuvalu",
    "slug":"tuvalu"
  },
  {
    degistir
 	"alpha2Code":"UG",
    "name":"Uganda",
    "slug":"uganda"
  },
  {
    degistir
 	"alpha2Code":"UA",
    "name":"Ukraine",
    "slug":"ukraine"
  },
  {
    degistir
 	"alpha2Code":"AE",
    "name":"United Arab Emirates",
    "slug":"united-arab-emirates"
  },
  {
    degistir
 	"alpha2Code":"GB",
    "name":"United Kingdom",
    "slug":"united-kingdom"
  },
  {
    degistir
 	"alpha2Code":"US",
    "name":"United States",
    "slug":"united-states"
  },
  {
    degistir
 	"alpha2Code":"VI",
    "name":"United States Virgin Islands",
    "slug":"united-states-virgin-islands"
  },
  {
    degistir
 	"alpha2Code":"UY",
    "name":"Uruguay",
    "slug":"uruguay"
  },
  {
    degistir
 	"alpha2Code":"UZ",
    "name":"Uzbekistan",
    "slug":"uzbekistan"
  },
  {
    degistir
 	"alpha2Code":"VU",
    "name":"Vanuatu",
    "slug":"vanuatu"
  },
  {
    degistir
 	"alpha2Code":"VA",
    "name":"Vatican City",
    "slug":"vatican-city"
  },
  {
    degistir
 	"alpha2Code":"VE",
    "name":"Venezuela",
    "slug":"venezuela"
  },
  {
    degistir
 	"alpha2Code":"VN",
    "name":"Vietnam",
    "slug":"vietnam"
  },
  {
    degistir
 	"alpha2Code":"WF",
    "name":"Wallis and Futuna",
    "slug":"wallis-and-futuna"
  },
  {
    degistir
 	"alpha2Code":"EH",
    "name":"Western Sahara",
    "slug":"western-sahara"
  },
  {
    degistir
 	"alpha2Code":"YE",
    "name":"Yemen",
    "slug":"yemen"
  },
  {
    degistir
 	"alpha2Code":"ZM",
    "name":"Zambia",
    "slug":"zambia"
  },
  {
    degistir
 	"alpha2Code":"ZW",
    "name":"Zimbabwe",
    "slug":"zimbabwe"
  }